// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToysStore.Data;

#nullable disable

namespace ToysStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628210445_CondizioneGiocattolo")]
    partial class CondizioneGiocattolo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ToysStore.Models.Auth.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ToysStore.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ToysStore.Models.Auth.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ToysStore.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("DescrizioneCategoria")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            DescrizioneCategoria = "Sonagli, tappeti gioco, giostrine, primi passi, cavalcabili, massaggiagengive.",
                            NomeCategoria = "Prima Infanzia (0-36 mesi)"
                        },
                        new
                        {
                            CategoriaId = 2,
                            DescrizioneCategoria = "LEGO, Mega Bloks, Playmobil, costruzioni in legno, set magnetici.",
                            NomeCategoria = "Costruzioni e Mattoncini"
                        },
                        new
                        {
                            CategoriaId = 3,
                            DescrizioneCategoria = "Supereroi, personaggi di film/serie TV, anime, wrestling, dinosauri, Gormiti.",
                            NomeCategoria = "Action Figure e Personaggi"
                        },
                        new
                        {
                            CategoriaId = 4,
                            DescrizioneCategoria = "Barbie, bambolotti (es. Cicciobello), case delle bambole, vestiti, passeggini giocattolo.",
                            NomeCategoria = "Bambole e Accessori"
                        },
                        new
                        {
                            CategoriaId = 5,
                            DescrizioneCategoria = "Orsacchiotti, personaggi animati in pezza, animali di peluche, doudou.",
                            NomeCategoria = "Peluche e Pupazzi"
                        },
                        new
                        {
                            CategoriaId = 6,
                            DescrizioneCategoria = "Giochi in scatola classici, giochi di carte, scacchi, dama.",
                            NomeCategoria = "Giochi da Tavolo e di Società"
                        },
                        new
                        {
                            CategoriaId = 7,
                            DescrizioneCategoria = "Puzzle tradizionali, puzzle 3D, cubi di Rubik, puzzle in legno.",
                            NomeCategoria = "Puzzle e Rompicapo"
                        },
                        new
                        {
                            CategoriaId = 8,
                            DescrizioneCategoria = "Macchinine (es. Hot Wheels), trenini, piste elettriche, droni, barche, aerei.",
                            NomeCategoria = "Veicoli, Radiocomandati e Piste"
                        },
                        new
                        {
                            CategoriaId = 9,
                            DescrizioneCategoria = "Microscopi, kit per esperimenti (STEM), mappamondi, tablet educativi, giochi di logica.",
                            NomeCategoria = "Educativi e Scientifici"
                        },
                        new
                        {
                            CategoriaId = 10,
                            DescrizioneCategoria = "Pasta da modellare (Play-Doh), kit per braccialetti, colori, lavagne, timbri.",
                            NomeCategoria = "Creatività, Arti e Mestieri"
                        },
                        new
                        {
                            CategoriaId = 11,
                            DescrizioneCategoria = "Cucine giocattolo, finti attrezzi da lavoro, registratori di cassa, set da dottore.",
                            NomeCategoria = "Giochi d'Imitazione e Ruolo"
                        },
                        new
                        {
                            CategoriaId = 12,
                            DescrizioneCategoria = "Vestiti di Carnevale/Halloween, maschere, bacchette magiche, accessori.",
                            NomeCategoria = "Costumi e Travestimenti"
                        },
                        new
                        {
                            CategoriaId = 13,
                            DescrizioneCategoria = "Biciclette, monopattini, pattini, palloni, pistole ad acqua, altalene, casette.",
                            NomeCategoria = "Sport e Giochi all'Aperto"
                        },
                        new
                        {
                            CategoriaId = 14,
                            DescrizioneCategoria = "Tastiere elettroniche, chitarre per bambini, xilofoni, batterie, microfoni.",
                            NomeCategoria = "Musica e Strumenti Giocattolo"
                        },
                        new
                        {
                            CategoriaId = 15,
                            DescrizioneCategoria = "Console (Nintendo Switch, PlayStation), videogiochi fisici, accessori gaming, Tamagotchi.",
                            NomeCategoria = "Videogiochi e Elettronica"
                        },
                        new
                        {
                            CategoriaId = 16,
                            DescrizioneCategoria = "Fiabe, libri interattivi, fumetti per ragazzi, dispositivi audio (Fabbrica delle Storie, Tonies).",
                            NomeCategoria = "Libri, Fumetti e Cantastorie"
                        },
                        new
                        {
                            CategoriaId = 17,
                            DescrizioneCategoria = "Zaini con personaggi, astucci, portapranzi, grembiuli.",
                            NomeCategoria = "Zaini e Articoli Scolastici"
                        });
                });

            modelBuilder.Entity("ToysStore.Models.Condizione", b =>
                {
                    b.Property<int>("CondizioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CondizioneId"));

                    b.Property<string>("DescrizioneCondizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeCondizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CondizioneId");

                    b.ToTable("Condizione");

                    b.HasData(
                        new
                        {
                            CondizioneId = 1,
                            DescrizioneCondizione = "Il giocattolo è nuovo, mai aperto e si trova nella sua confezione originale con i sigilli intatti. Non presenta alcun danno.",
                            NomeCondizione = "Nuovo e sigillato"
                        },
                        new
                        {
                            CondizioneId = 2,
                            DescrizioneCondizione = "Il giocattolo non è mai stato usato per giocare, ma non ha più la scatola originale o le etichette. Non presenta il minimo segno di usura ed è completo di tutti gli accessori.",
                            NomeCondizione = "Nuovo senza confezione"
                        },
                        new
                        {
                            CondizioneId = 3,
                            DescrizioneCondizione = "Usato pochissimo e tenuto con cura. Non ci sono difetti visibili, graffi o scoloriture. Tutti i pezzi originali sono presenti e, se elettronico, funziona perfettamente.",
                            NomeCondizione = "Ottimo"
                        },
                        new
                        {
                            CondizioneId = 4,
                            DescrizioneCondizione = "Il giocattolo è stato usato e amato. Mostra segni di usura normali e leggeri (es. piccoli graffi superficiali o adesivi leggermente consumati). È comunque completo per poterci giocare e strutturalmente integro.",
                            NomeCondizione = "Buono"
                        },
                        new
                        {
                            CondizioneId = 5,
                            DescrizioneCondizione = "Mostra segni di usura evidenti dovuti a un uso frequente. Potrebbe avere graffi profondi, vernice scolorita o mancare di accessori non essenziali (che non impediscono il funzionamento principale del gioco).",
                            NomeCondizione = "Accettabile"
                        },
                        new
                        {
                            CondizioneId = 6,
                            DescrizioneCondizione = "Il giocattolo presenta difetti importanti, componenti elettroniche non funzionanti, rotture o pezzi mancanti fondamentali. Viene venduto principalmente per essere riparato, riutilizzato per parti di ricambio (es. lotti di mattoncini Lego) o restauro.",
                            NomeCondizione = "Con difetti"
                        });
                });

            modelBuilder.Entity("ToysStore.Models.ImmagineProdotto", b =>
                {
                    b.Property<Guid>("ImmagineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProdottoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlImmagine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImmagineId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("ImmaginiProdotto");
                });

            modelBuilder.Entity("ToysStore.Models.IndirizzoUtente", b =>
                {
                    b.Property<Guid>("IndirizzoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPredefinito")
                        .HasColumnType("bit");

                    b.Property<string>("NomeIndirizzo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IndirizzoId");

                    b.HasIndex("UserId");

                    b.ToTable("IndirizziUtenti");
                });

            modelBuilder.Entity("ToysStore.Models.Ordine", b =>
                {
                    b.Property<Guid>("OrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CAPSnapshot")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CittaSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndirizzoSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatoOrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Totale")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrdineId");

                    b.HasIndex("StatoOrdineId");

                    b.HasIndex("UserId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("ToysStore.Models.Prodotto", b =>
                {
                    b.Property<Guid>("GiocattoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CondizioneId")
                        .HasColumnType("int");

                    b.Property<string>("DescrizioneGiocattolo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NomeGiocattolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrezzoGiocattolo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GiocattoloId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CondizioneId");

                    b.HasIndex("UserId");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("ToysStore.Models.ProdottoCarrello", b =>
                {
                    b.Property<Guid>("ProdottoCarrelloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdottoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProdottoCarrelloId");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("UserId");

                    b.ToTable("ProdottiCarrello");
                });

            modelBuilder.Entity("ToysStore.Models.ProdottoOrdine", b =>
                {
                    b.Property<int>("ProdottoOrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdottoOrdineId"));

                    b.Property<Guid>("OrdineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdottoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("ProdottoOrdineId");

                    b.HasIndex("OrdineId");

                    b.HasIndex("ProdottoId");

                    b.ToTable("ProdottiOrdine");
                });

            modelBuilder.Entity("ToysStore.Models.RecensioneProdotto", b =>
                {
                    b.Property<Guid>("RecensioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRecensione")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProdottoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecensioneTesto")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Valutazione")
                        .HasColumnType("int");

                    b.HasKey("RecensioneId");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("UserId");

                    b.ToTable("RecensioniProdotto");
                });

            modelBuilder.Entity("ToysStore.Models.StatoOrdine", b =>
                {
                    b.Property<int>("StatoOrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatoOrdineId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatoOrdineId");

                    b.ToTable("StatiOrdine");

                    b.HasData(
                        new
                        {
                            StatoOrdineId = 1,
                            Nome = "In Attesa"
                        },
                        new
                        {
                            StatoOrdineId = 2,
                            Nome = "Confermato"
                        },
                        new
                        {
                            StatoOrdineId = 3,
                            Nome = "In Preparazione"
                        },
                        new
                        {
                            StatoOrdineId = 4,
                            Nome = "Spedito"
                        },
                        new
                        {
                            StatoOrdineId = 5,
                            Nome = "Ricevuto"
                        },
                        new
                        {
                            StatoOrdineId = 6,
                            Nome = "Annullato"
                        });
                });

            modelBuilder.Entity("ToysStore.Models.Utente", b =>
                {
                    b.Property<Guid>("UtenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImmagineProfilo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UtenteId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToysStore.Models.Auth.ApplicationUserRole", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationRole", "ApplicationRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ToysStore.Models.ImmagineProdotto", b =>
                {
                    b.HasOne("ToysStore.Models.Prodotto", "Prodotto")
                        .WithMany("ImmaginiProdotto")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("ToysStore.Models.IndirizzoUtente", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "User")
                        .WithMany("Indirizzi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToysStore.Models.Ordine", b =>
                {
                    b.HasOne("ToysStore.Models.StatoOrdine", "StatoOrdine")
                        .WithMany("Ordini")
                        .HasForeignKey("StatoOrdineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "User")
                        .WithMany("Ordini")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatoOrdine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToysStore.Models.Prodotto", b =>
                {
                    b.HasOne("ToysStore.Models.Categoria", "Categoria")
                        .WithMany("Prodotti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Condizione", "Condizione")
                        .WithMany("Prodotti")
                        .HasForeignKey("CondizioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "User")
                        .WithMany("ListaProdotti")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Condizione");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToysStore.Models.ProdottoCarrello", b =>
                {
                    b.HasOne("ToysStore.Models.Prodotto", "Prodotto")
                        .WithMany("ProdottiCarrello")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "User")
                        .WithMany("ProdottiCarrello")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToysStore.Models.ProdottoOrdine", b =>
                {
                    b.HasOne("ToysStore.Models.Ordine", "Ordine")
                        .WithMany("ProdottiOrdine")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Prodotto", "Prodotto")
                        .WithMany("ProdottiOrdine")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("ToysStore.Models.RecensioneProdotto", b =>
                {
                    b.HasOne("ToysStore.Models.Prodotto", "Prodotto")
                        .WithMany("RecensioniProdotto")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "User")
                        .WithMany("RecensioniProdotto")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToysStore.Models.Utente", b =>
                {
                    b.HasOne("ToysStore.Models.Auth.ApplicationUser", "User")
                        .WithOne("Utente")
                        .HasForeignKey("ToysStore.Models.Utente", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToysStore.Models.Auth.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ToysStore.Models.Auth.ApplicationUser", b =>
                {
                    b.Navigation("Indirizzi");

                    b.Navigation("ListaProdotti");

                    b.Navigation("Ordini");

                    b.Navigation("ProdottiCarrello");

                    b.Navigation("RecensioniProdotto");

                    b.Navigation("UserRoles");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("ToysStore.Models.Categoria", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("ToysStore.Models.Condizione", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("ToysStore.Models.Ordine", b =>
                {
                    b.Navigation("ProdottiOrdine");
                });

            modelBuilder.Entity("ToysStore.Models.Prodotto", b =>
                {
                    b.Navigation("ImmaginiProdotto");

                    b.Navigation("ProdottiCarrello");

                    b.Navigation("ProdottiOrdine");

                    b.Navigation("RecensioniProdotto");
                });

            modelBuilder.Entity("ToysStore.Models.StatoOrdine", b =>
                {
                    b.Navigation("Ordini");
                });
#pragma warning restore 612, 618
        }
    }
}
